name: demo_firebase_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.1
  firebase_database: ^11.3.6
  intl: ^0.18.1
  google_fonts: ^6.1.0
  fl_chart: ^0.63.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/steam_logo.png

